name: Deploy Frontend to ECR and EKS

on:
  push:
    branches:
      - deploy
    paths:
      - 'proyecto semestral/front_despacho/**'
      - 'kubernetes/03-frontend.yaml'
      - 'kubernetes/04-autoscaling.yaml'
      - '.github/workflows/frontend-deploy.yml'



jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        uses: docker/build-push-action@v5
        with:
          context: "./proyecto semestral/front_despacho"
          file: "./proyecto semestral/front_despacho/Dockerfile"
          push: true
          tags: |
            ${{ secrets.ECR_REPO_URL_FRONTEND }}:latest
            ${{ secrets.ECR_REPO_URL_FRONTEND }}:${{ github.sha }}

# ==== CONFIGURACIÓN DE CD (DESPLIEGUE A AMAZON EKS) ====
      - name: Update Kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --name devopseks --region us-east-1

      - name: Deploy to EKS Clúster
        run: |
          sed -i 's|nginx:latest|${{ secrets.ECR_REPO_URL_FRONTEND }}:${{ github.sha }}|g' kubernetes/03-frontend.yaml
          kubectl apply -f kubernetes/03-frontend.yaml

      - name: FOTOS PARA DIAPOSITIVA 3 (Evidencia de Orquestación)
        run: |
          echo "Esperando a que los contenedores enciendan..."
          sleep 15
          
          echo "========================================="
          echo "📸 FOTO 1: TUS MÁQUINAS (NODOS)"
          echo "========================================="
          kubectl get nodes -o wide
          
          echo ""
          echo "========================================="
          echo "📸 FOTO 2: TUS CONTENEDORES (PODS)"
          echo "========================================="
          kubectl get pods -n innovatech
      - name: Obtener URL del Balanceador de Carga
        run: |
          echo "Esperando 20 segundos para que AWS cree el nuevo balanceador..."
          sleep 20
          kubectl get svc frontend-service -n innovatech

      - name: Describir Servicio Frontend (Debugging)
        run: |
          kubectl describe svc frontend-service -n innovatech

