name: Deploy Frontend to AWS ECS

on:
  push:
    branches:
      - deploy
      - main
    paths:
      - 'proyecto semestral/front_despacho/**'

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push Frontend image to Amazon ECR
        uses: docker/build-push-action@v5
        with:
          context: "./proyecto semestral/front_despacho"
          file: "./proyecto semestral/front_despacho/Dockerfile"
          push: true
          tags: |
            ${{ secrets.ECR_REPO_URL_FRONTEND }}:latest
            ${{ secrets.ECR_REPO_URL_FRONTEND }}:${{ github.sha }}

      - name: Download active task definition for Frontend
        run: |
          aws ecs describe-task-definition --task-definition ${{ secrets.ECS_TASK_DEFINITION_FRONTEND }} --query taskDefinition > task-def-frontend.json

      - name: Fill in the new image ID in the Frontend task definition
        id: render-frontend
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-def-frontend.json
          container-name: ${{ secrets.ECS_CONTAINER_NAME_FRONTEND }}
          image: ${{ secrets.ECR_REPO_URL_FRONTEND }}:${{ github.sha }}

      - name: Deploy Frontend to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.render-frontend.outputs.task-definition }}
          service: ${{ secrets.ECS_SERVICE_NAME_FRONTEND }}
          cluster: ${{ secrets.ECS_CLUSTER_NAME }}
          wait-for-service-stability: true
